service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - sqs:*
        - comprehend:*
      Resource: "*"

functions:
  getMyHistory:
    handler: handler.getMyHistory
    memorySize: 128